PinsNamepack = []
PinsNumpack  = []
IONamepack = [] # Getting the io name pack 
Packagingdata = {} 
PackagewithIO = {} 
completepack = {} 
completeioname = {} 
check_datatype = {}
Check_Packagename = []  # Checking the list of the package name inside the list 
Generate_Pinspack = []
Generate_Numpack = [] 
Generate_iopack = [] 
completeNumpack = {} # Getting the new pins name append into the dictionary 
completePinspack = {} #Getting the complete pins pack data
check_pack_order = {}   
check_pins_table = {} #Getting the pins table inside the list 
Pack_data = {}
